In [1]:
import pandas as pd
import numpy as np
import json
from jinja2 import Environment, FileSystemLoader

In [2]:
def table_data_format(df_orig):
    metadata = []
    df = df_orig
    df.replace(to_replace=["na", "?", np.nan, "missing", "not available",
                           "n/a", "missing value"], value=np.nan, inplace=True)

    for col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='ignore')

    for idx, col in enumerate(df.columns):
        helper = {}
        key = col
        if len(key) > 15:
            key = col[:15]

        helper['ascend'] = 0
        helper['name'] = key
        if(df.dtypes[col] == "object"):
            df[col].replace(to_replace=["na", "?", np.nan, "missing", "not available",
                                        "n/a", "missing value"], value="missing value", inplace=True)
            helper['datatype'] = 'string'
            helper['values'] = df[col].unique().tolist()
        elif(df.dtypes[col] == "int64"):
            helper['datatype'] = 'int'
            helper['min_val'] = df[col].min()
            helper['max_val'] = df[col].max()
        elif(df.dtypes[col] == "float64"):
            helper['datatype'] = 'float'
            helper['min_val'] = df[col].min()
            helper['max_val'] = df[col].max()
        metadata.append(helper)

    df.replace(to_replace=["na", "?", np.nan, "missing", "not available",
                           "n/a", "missing value"], value="missing value", inplace=True)
    data_array = []
    for row in range(df.shape[0]):
        aux = []
        for col in range(df.shape[1]):
            aux.append(df.iloc[row, col])
        data_array.append(aux)
    return metadata, data_array

In [3]:
path = r'C:\Users\Luis_Dutra\3D Objects\datasets\enem\enem_2019_for_table_viz.csv'

# Ler quantidade determinada de linhas do dataset
df = pd.read_csv(path)

df

,NU_INSCRICAO,NU_IDADE,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,TP_NACIONALIDADE,SG_UF_NASCIMENTO,TP_ST_CONCLUSAO,TP_ANO_CONCLUIU,TP_ESCOLA,...,NU_NOTA_CH,NU_NOTA_LC,NU_NOTA_MT,TP_LINGUA,TP_STATUS_REDACAO,NU_NOTA_REDACAO,Q001,Q002,Q006,Q025
0,190001043648,19,M,Solteiro(a),Parda,Brasileiro(a),RS,Já concluí o Ensino Médio,2018,Não Respondeu,...,582.1,544.5,680.7,Espanhol,Sem problemas,760.0,Completou a Pós-graduação.,"Completou a Faculdade, mas não completou a Pós...",9 a 10 SM,Sim
1,190001684765,35,F,Casado(a)/Mora com companheiro(a),Branca,Brasileiro(a),RS,Já concluí o Ensino Médio,Antes de 2007,Não Respondeu,...,538.5,546.8,367.3,Espanhol,Sem problemas,640.0,Completou a 8ª série/9º ano do Ensino Fundamen...,"Completou a 4ª série/5º ano, mas não completou...",1 SM,Sim
2,190001684774,18,F,Não informado,Branca,Brasileiro(a),RS,Estou cursando e concluirei o Ensino Médio em ...,Não informado,Pública,...,529.1,526.9,412.6,Inglês,Sem problemas,660.0,"Completou o Ensino Médio, mas não completou a ...","Completou o Ensino Médio, mas não completou a ...",2.5 a 3 SM,Sim
3,190001684779,24,M,Solteiro(a),Branca,Brasileiro(a),RS,Já concluí o Ensino Médio,2014,Não Respondeu,...,464.7,535.7,659.7,Inglês,Sem problemas,800.0,Não completou a 4ª série/5º ano do Ensino Fund...,"Completou o Ensino Médio, mas não completou a ...",1 SM,Sim
4,190001684793,20,F,Solteiro(a),Branca,Brasileiro(a),RS,Já concluí o Ensino Médio,2017,Não Respondeu,...,537.0,557.6,393.6,Inglês,Sem problemas,620.0,"Completou o Ensino Médio, mas não completou a ...",Completou a 8ª série/9º ano do Ensino Fundamen...,2 a 2.5 SM,Sim
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21197,190006117762,18,M,Solteiro(a),Branca,Brasileiro(a),RS,Estou cursando e concluirei o Ensino Médio em ...,Não informado,Pública,...,420.6,545.6,650.4,Espanhol,Sem problemas,400.0,"Completou o Ensino Médio, mas não completou a ...","Completou o Ensino Médio, mas não completou a ...",3 a 4 SM,Sim
21198,190006117777,18,M,Solteiro(a),Branca,Brasileiro(a),RS,Estou cursando e concluirei o Ensino Médio em ...,Não informado,Pública,...,548.2,538.5,557.6,Espanhol,Sem problemas,560.0,"Completou o Ensino Médio, mas não completou a ...","Completou a Faculdade, mas não completou a Pós...",3 a 4 SM,Sim
21199,190006119127,16,M,Solteiro(a),Branca,Brasileiro(a),RS,Estou cursando e concluirei o Ensino Médio apó...,Não informado,Não Respondeu,...,425.3,520.5,604.2,Espanhol,Sem problemas,560.0,Não completou a 4ª série/5º ano do Ensino Fund...,Não completou a 4ª série/5º ano do Ensino Fund...,1 a 1.5 SM,Sim
21200,190006119133,17,M,Solteiro(a),Parda,Brasileiro(a),BA,Estou cursando e concluirei o Ensino Médio em ...,Não informado,Pública,...,461.0,558.2,586.5,Inglês,Parte desconectada,0.0,"Completou a 4ª série/5º ano, mas não completou...","Completou a Faculdade, mas não completou a Pós...",2 a 2.5 SM,Sim
21201,190006119150,19,M,Solteiro(a),Branca,Brasileiro(a),RS,Já concluí o Ensino Médio,2017,Não Respondeu,...,547.3,610.7,752.9,Inglês,Sem problemas,740.0,"Completou o Ensino Médio, mas não completou a ...","Completou a Faculdade, mas não completou a Pós...",4 a 5 SM,Sim

In [5]:
def corrigir_palavras(nome):
    nome = nome.replace('.', '').replace('ç', 'c').replace('ô', 'o').replace('é', 'e').replace('ã','a').replace('ê','e').replace('í','i').replace('ì','').replace('Ì','I').replace('Í','I').replace('í','i').replace('ì','').replace('ó','o').replace('ò','o').replace('ú','u').replace('u','ù').replace('á','a')
            
    return nome

In [7]:
df['TP_SEXO'] = df['TP_SEXO'].apply(corrigir_palavras)
df['TP_ESTADO_CIVIL'] = df['TP_ESTADO_CIVIL'].apply(corrigir_palavras)
df['TP_COR_RACA'] = df['TP_COR_RACA'].apply(corrigir_palavras)
df['TP_NACIONALIDADE'] = df['TP_NACIONALIDADE'].apply(corrigir_palavras)
df['SG_UF_NASCIMENTO'] = df['SG_UF_NASCIMENTO'].apply(corrigir_palavras)
df['TP_ST_CONCLUSAO'] = df['TP_ST_CONCLUSAO'].apply(corrigir_palavras)
df['TP_ANO_CONCLUIU'] = df['TP_ANO_CONCLUIU'].apply(corrigir_palavras)
df['TP_ESCOLA'] = df['TP_ESCOLA'].apply(corrigir_palavras)
df['TP_ENSINO'] = df['TP_ENSINO'].apply(corrigir_palavras)
df['IN_TREINEIRO'] = df['IN_TREINEIRO'].apply(corrigir_palavras)
df['TP_DEPENDENCIA_ADM_ESC'] = df['TP_DEPENDENCIA_ADM_ESC'].apply(corrigir_palavras)
df['TP_LOCALIZACAO_ESC'] = df['TP_LOCALIZACAO_ESC'].apply(corrigir_palavras)
df['TP_SIT_FUNC_ESC'] = df['TP_SIT_FUNC_ESC'].apply(corrigir_palavras)
df['IN_SURDEZ'] = df['IN_SURDEZ'].apply(corrigir_palavras)
df['IN_SURDO_CEGUEIRA'] = df['IN_SURDO_CEGUEIRA'].apply(corrigir_palavras)
df['IN_DEFICIENCIA_FISICA'] = df['IN_DEFICIENCIA_FISICA'].apply(corrigir_palavras)
df['IN_DEFICIENCIA_MENTAL'] = df['IN_DEFICIENCIA_MENTAL'].apply(corrigir_palavras)
df['IN_DEFICIT_ATENCAO'] = df['IN_DEFICIT_ATENCAO'].apply(corrigir_palavras)
df['IN_DISLEXIA'] = df['IN_DISLEXIA'].apply(corrigir_palavras)
df['IN_DISCALCULIA'] = df['IN_DISCALCULIA'].apply(corrigir_palavras)
df['IN_AUTISMO'] = df['IN_AUTISMO'].apply(corrigir_palavras)
df['IN_GESTANTE'] = df['IN_GESTANTE'].apply(corrigir_palavras)
df['TP_LINGUA'] = df['TP_LINGUA'].apply(corrigir_palavras)
df['TP_STATUS_REDACAO'] = df['TP_STATUS_REDACAO'].apply(corrigir_palavras)
df['Q001'] = df['Q001'].apply(corrigir_palavras)
df['Q002'] = df['Q002'].apply(corrigir_palavras)
df['Q006'] = df['Q006'].apply(corrigir_palavras)
df['Q025'] = df['Q025'].apply(corrigir_palavras)

In [8]:
del df['NU_INSCRICAO']

In [9]:
# Adiciona o  metadata_table_viz e dataarray_table_viz no html

file_loader = FileSystemLoader(r'C:\pandas-profiling\pandas_profiling\templates')
env = Environment(loader=file_loader)

template = env.get_template("table.html")

keys, data_array = table_data_format(df)

output = template.render(metadata_table_viz=keys, dataarray_table_viz=data_array)

# C:\pandas-profiling\notebook
with open("test.html", "w") as result_file:
    result_file.write(output)